services:
  gateway:
    build: ./gateway
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - stakeholders
      - blog
      - purchase
      - followers
    networks:
      - soa-net

  auth:
    build:
      context: ./auth
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
      APP_ADMIN_USERNAME: admin
      APP_ADMIN_PASSWORD: admin
      APP_ADMIN_EMAIL: admin@example.com
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - soa-net

  stakeholders:
    build:
      context: ./stakeholders
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
      GRPC_SERVER_PORT: 9090
    ports:
      - "9090:9090"
    depends_on:
      - stakeholders-db
      - rabbitmq
    networks:
      - soa-net

  blog:
    build:
      context: ./blog
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - blog-db
      - rabbitmq
    networks:
      - soa-net

  tour:
    build:
      context: ./tour
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - tour-db
      - rabbitmq
    networks:
      - soa-net

  purchase:
    build:
      context: ./purchase
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - purchase-db
      - rabbitmq
    networks:
      - soa-net

  followers:
    build:
      context: ./followers
    environment:
      NEO4J_URI: bolt://followers-db:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - followers-db
      - rabbitmq
    networks:
      - soa-net

  auth-db:
    image: postgres:17
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-net

  stakeholders-db:
    image: postgres:17
    environment:
      POSTGRES_DB: stakeholders-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stakeholders_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-net

  blog-db:
    image: mongo:8
    volumes:
      - blog_mongo_data:/data/db
    networks:
      - soa-net

  tour-db:
    image: postgres:17
    environment:
      POSTGRES_DB: tour-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - tour_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-net

  purchase-db:
    image: postgres:17
    environment:
      POSTGRES_DB: purchase-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - purchase_postgres_data:/var/lib/postgresql/data
    networks:
      - soa-net

  followers-db:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - soa-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    depends_on:
      - auth-db
      - stakeholders-db
      - tour-db
      - purchase-db
    networks:
      - soa-net

  rabbitmq:
    image: rabbitmq:4.2.5-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
        - soa-net

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9091:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - auth
      - stakeholders
      - blog
      - tour
      - purchase
      - followers
      - node-exporter
      - cadvisor
    networks:
      - soa-net

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - soa-net

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    networks:
      - soa-net

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./observability/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - soa-net

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo/tempo.yml
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo
    networks:
      - soa-net

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - soa-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - soa-net

volumes:
  auth_postgres_data:
  stakeholders_postgres_data:
  blog_mongo_data:
  tour_postgres_data:
  purchase_postgres_data:
  neo4j_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:

networks:
  soa-net:
