services:
  gateway:
    build: ./gateway
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - stakeholders
      - blog
    networks:
      - soa-net

  auth:
    build:
      context: ./auth
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - soa-net

  stakeholders:
    build:
      context: ./stakeholders
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - stakeholders-db
      - rabbitmq
    networks:
      - soa-net

  blog:
    build:
      context: ./blog
    environment:
      JWT_SECRET: my-super-long-secret-key-that-is-at-least-64-characters-long-123456
    depends_on:
      - blog-db
      - rabbitmq
    networks:
      - soa-net

  auth-db:
    image: postgres
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - soa-net

  stakeholders-db:
    image: postgres
    environment:
      POSTGRES_DB: stakeholders-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - soa-net

  blog-db:
    image: postgres
    environment:
      POSTGRES_DB: blog-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - soa-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    depends_on:
      - auth-db
      - blog-db
      - stakeholders-db
    networks:
      - soa-net

  rabbitmq:
    image: rabbitmq:4.2.5-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
    networks:
        - soa-net

networks:
  soa-net: